services:
  backend:
    build: ./backend
    container_name: projeto-backend
    ports:
      - "8080:8080"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/GRUPO01banco?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: GRUPO01usuario
      SPRING_DATASOURCE_PASSWORD: GRUPO01senhausuario
    depends_on:
      - db

  # Quando adicionar o frontend, criar um dockerfile para o mesmo e descomentar essa parte abaixo.
  #  frontend:
  #    build: ./frontend
  #    container_name: projeto-frontend
  #    ports:
  #      - "3000:80"
  #    depends_on:
  #      - backend
  #    restart: always

  db:
    image: mysql:8.0
    container_name: projeto-db
    environment:
      MYSQL_ROOT_PASSWORD: GRUPO01senha
      MYSQL_DATABASE: GRUPO01banco
      MYSQL_USER: GRUPO01usuario
      MYSQL_PASSWORD: GRUPO01senhausuario
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
    driver: local
